from __future__ import annotations

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
   
    question: str = Field(
        ...,
        min_length=3,
        description="Natural language business question.",
    )


class RetryAttemptResponse(BaseModel):
   

    attempt_number: int = Field(
        description="Retry attempt number."
    )

    original_sql: str = Field(
        description="SQL that failed."
    )

    error: str = Field(
        description="Database error returned by PostgreSQL."
    )

    corrected_sql: str = Field(
        description="SQL generated by the retry agent."
    )

    reasoning: str = Field(
        description="Explanation of the correction."
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Retry agent confidence score.",
    )

    detected_error: str = Field(
        description="Detected SQL error category."
    )

    changes_made: list[str] = Field(
        default_factory=list,
        description="List of modifications applied to the SQL query.",
    )


class QueryResponse(BaseModel):
    

    question: str

    tables: list[str] = Field(
        default_factory=list,
        description="Relevant tables used to answer the question.",
    )

    reasoning: str = Field(
        description="Schema exploration reasoning."
    )

    sql_query: str = Field(
        description="Final SQL executed successfully."
    )

    explanation: str = Field(
    description="Natural language explanation generated by Explanation Agent."
     )
    rows: list[dict] = Field(
        default_factory=list,
        description="Returned database rows.",
    )

    columns: list[str] = Field(
        default_factory=list,
        description="Column names.",
    )

    row_count: int = Field(
        description="Number of rows returned."
    )

    execution_time_ms: float = Field(
        description="Database execution time in milliseconds.",
    )

    total_time_ms: float = Field(
        description="Complete workflow execution time.",
    )

    retry_count: int = Field(
        description="Number of SQL retries performed."
    )

    retry_history: list[RetryAttemptResponse] = Field(
        default_factory=list,
        description="History of retry attempts.",
    )

   


class HealthResponse(BaseModel):
    

    status: str = Field(
        description="Overall API status."
    )

    database: bool = Field(
        description="Database connection status."
    )

    llm: bool = Field(
        description="LLM availability."
    )